//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apptab1
    {
        public int Appid { get; set; }
        public int Userid { get; set; }
        public int Jobid { get; set; }
        public string Cv { get; set; }
        public string Appdate { get; set; }
        public string Appstatus { get; set; }
    }
}
