//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compreg
    {
        public int Cid { get; set; }
        public string Cname { get; set; }
        public string Caddress { get; set; }
        public string Cphone { get; set; }
        public string Cemail { get; set; }
        public string Cwebsite { get; set; }
        public string Clocation { get; set; }
    }
}
