//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobtab
    {
        public int Jobid { get; set; }
        public int Cid { get; set; }
        public string Jobtitle { get; set; }
        public string JExperience { get; set; }
        public string JSkills { get; set; }
        public string Vacancy { get; set; }
        public string Date { get; set; }
        public string JStatus { get; set; }
        public string JLocation { get; set; }
    }
}
