//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logtab
    {
        public int Logid { get; set; }
        public int Regid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Logtype { get; set; }
        public string Status { get; set; }
    }
}
