//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVCProject2Entities : DbContext
    {
        public MVCProject2Entities()
            : base("name=MVCProject2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apptab> Apptabs { get; set; }
        public virtual DbSet<Compreg> Compregs { get; set; }
        public virtual DbSet<Jobtab> Jobtabs { get; set; }
        public virtual DbSet<Logtab> Logtabs { get; set; }
        public virtual DbSet<Userreg> Userregs { get; set; }
        public virtual DbSet<Logtab1> Logtab1 { get; set; }
        public virtual DbSet<Apptab1> Apptab1 { get; set; }
    
        public virtual int sp_company(Nullable<int> cid, string cname, string caddr, string cphone, string cemail, string cwebsite, string clocation)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var caddrParameter = caddr != null ?
                new ObjectParameter("caddr", caddr) :
                new ObjectParameter("caddr", typeof(string));
    
            var cphoneParameter = cphone != null ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            var cwebsiteParameter = cwebsite != null ?
                new ObjectParameter("cwebsite", cwebsite) :
                new ObjectParameter("cwebsite", typeof(string));
    
            var clocationParameter = clocation != null ?
                new ObjectParameter("clocation", clocation) :
                new ObjectParameter("clocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_company", cidParameter, cnameParameter, caddrParameter, cphoneParameter, cemailParameter, cwebsiteParameter, clocationParameter);
        }
    
        public virtual int sp_log(Nullable<int> rid, string uname, string pwd, string lgtype, string lgsts)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var lgtypeParameter = lgtype != null ?
                new ObjectParameter("lgtype", lgtype) :
                new ObjectParameter("lgtype", typeof(string));
    
            var lgstsParameter = lgsts != null ?
                new ObjectParameter("lgsts", lgsts) :
                new ObjectParameter("lgsts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_log", ridParameter, unameParameter, pwdParameter, lgtypeParameter, lgstsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logmaxid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logmaxid");
        }
    
        public virtual int sp_userreg(Nullable<int> uid, string una, Nullable<int> uag, string uaddr, string uphone, string uemail, string uqual, string uexp, string uskill, string upic, string ures)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var uagParameter = uag.HasValue ?
                new ObjectParameter("uag", uag) :
                new ObjectParameter("uag", typeof(int));
    
            var uaddrParameter = uaddr != null ?
                new ObjectParameter("uaddr", uaddr) :
                new ObjectParameter("uaddr", typeof(string));
    
            var uphoneParameter = uphone != null ?
                new ObjectParameter("uphone", uphone) :
                new ObjectParameter("uphone", typeof(string));
    
            var uemailParameter = uemail != null ?
                new ObjectParameter("uemail", uemail) :
                new ObjectParameter("uemail", typeof(string));
    
            var uqualParameter = uqual != null ?
                new ObjectParameter("uqual", uqual) :
                new ObjectParameter("uqual", typeof(string));
    
            var uexpParameter = uexp != null ?
                new ObjectParameter("uexp", uexp) :
                new ObjectParameter("uexp", typeof(string));
    
            var uskillParameter = uskill != null ?
                new ObjectParameter("uskill", uskill) :
                new ObjectParameter("uskill", typeof(string));
    
            var upicParameter = upic != null ?
                new ObjectParameter("upic", upic) :
                new ObjectParameter("upic", typeof(string));
    
            var uresParameter = ures != null ?
                new ObjectParameter("ures", ures) :
                new ObjectParameter("ures", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userreg", uidParameter, unaParameter, uagParameter, uaddrParameter, uphoneParameter, uemailParameter, uqualParameter, uexpParameter, uskillParameter, upicParameter, uresParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> loginid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("loginid", unaParameter, pwdParameter);
        }
    
        public virtual int sp_logcount(string una, string pwd, ObjectParameter lgsts)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logcount", unaParameter, pwdParameter, lgsts);
        }
    
        public virtual ObjectResult<string> sp_logtype(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logtype", unaParameter, pwdParameter);
        }
    
        public virtual int sp_logg(Nullable<int> rid, string uname, string pwd, string lgtype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var lgtypeParameter = lgtype != null ?
                new ObjectParameter("lgtype", lgtype) :
                new ObjectParameter("lgtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logg", ridParameter, unameParameter, pwdParameter, lgtypeParameter);
        }
    
        public virtual int sp_jobadd(Nullable<int> cid, string jtle, string jexp, string jskill, string jvaca, string jdate, string jsts, string jlocation)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jtleParameter = jtle != null ?
                new ObjectParameter("jtle", jtle) :
                new ObjectParameter("jtle", typeof(string));
    
            var jexpParameter = jexp != null ?
                new ObjectParameter("jexp", jexp) :
                new ObjectParameter("jexp", typeof(string));
    
            var jskillParameter = jskill != null ?
                new ObjectParameter("jskill", jskill) :
                new ObjectParameter("jskill", typeof(string));
    
            var jvacaParameter = jvaca != null ?
                new ObjectParameter("jvaca", jvaca) :
                new ObjectParameter("jvaca", typeof(string));
    
            var jdateParameter = jdate != null ?
                new ObjectParameter("jdate", jdate) :
                new ObjectParameter("jdate", typeof(string));
    
            var jstsParameter = jsts != null ?
                new ObjectParameter("jsts", jsts) :
                new ObjectParameter("jsts", typeof(string));
    
            var jlocationParameter = jlocation != null ?
                new ObjectParameter("jlocation", jlocation) :
                new ObjectParameter("jlocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobadd", cidParameter, jtleParameter, jexpParameter, jskillParameter, jvacaParameter, jdateParameter, jstsParameter, jlocationParameter);
        }
    
        public virtual int sp_searchjobs(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_searchjobs", qryParameter);
        }
    
        public virtual int sp_appdata(Nullable<int> usrid, Nullable<int> jid, string cv, string appdate, string appsts)
        {
            var usridParameter = usrid.HasValue ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var appdateParameter = appdate != null ?
                new ObjectParameter("appdate", appdate) :
                new ObjectParameter("appdate", typeof(string));
    
            var appstsParameter = appsts != null ?
                new ObjectParameter("appsts", appsts) :
                new ObjectParameter("appsts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_appdata", usridParameter, jidParameter, cvParameter, appdateParameter, appstsParameter);
        }
    }
}
