//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userreg
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string Skills { get; set; }
        public string Photo { get; set; }
        public string Resume { get; set; }
    }
}
